language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4
  - ctest --verbose

notifications:
  email:
    on_success: never
    on_failure: never
