language: generic
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libboost-all-dev
      - cmake

env:
    - CC=gcc-5 CXX=g++-5

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4
  - make test

notifications:
  email:
    on_success: never
    on_failure: never
